### ISSUE TITLE
[QUESTION] why only python 3.9?

### ISSUE THREAD

**Issue by pp0236** [coverosu/local-osu-server#11]
i try 3.10 and 3.11 and it has no problem while running server

**Comment by coverosu** [comment]
I think when I was originally making it, python 11 was unstable and i was using py3.9 exclusive packages iirc, it's been forever tho so I wouldn't know 😭

**Comment by pp0236** [comment]
thanks for reply,
but i not recommend to change from 3.9 to newer version currently (3.10 might ok but not 3.11) because some package like orjson and aiohttp on 3.11 still has no precompile binrary yet, ppl will need c/rust compiler to install requirements

maybe just remove "2. You will most likely need to uninstall python3.10 from your system, due to instability"

**Comment by coverosu** [comment]
just removed! thanks for the issue :)

**Comment by pp0236** [comment]
thanks for reply,
but i not recommend to change from 3.9 to newer version currently (3.10
might ok but not 3.11) because some package like orjson and aiohttp on 3.11
still has no precompile binrary yet, ppl will need c/rust compiler to
install requirements

will close issue when im back

**Comment by coverosu** [comment]
thank you for letting me know. I'll probably be using 3.10 most likely in the v2 rewrite.
