### ISSUE TITLE
stuck on connection failed.

### ISSUE THREAD

**Issue by SrIzan10** [coverosu/local-osu-server#8]
hey! i run the server on a vmware virtual machine with windows server 2022 installed.

i've port fowarded the :5000 port on TCP and UDP.

i connect with localhost:5000 and it doesn't want to work! any ideas?

thanks!

(and sorry for bothering you so much today)

**Comment by coverosu** [comment]
oh uh the server isn't meant to be port forwarded cause it only handles http connections, wherever you are playing osu on you should run the server on that machine. 

For the devserver method did you use `coverbancho.tk` as the domain?

**Comment by SrIzan10** [comment]
yes, but it was stuck on "Connecting to Bancho..."

**Comment by SrIzan10** [comment]
and i was thinking of using the server to play with my friends, i think this isn't the right project! 😅

**Comment by coverosu** [comment]
restart the server a couple times and you'll be fine I think cause that's what I had to do lol
> yes, but it was stuck on "Connecting to Bancho..."

**Comment by coverosu** [comment]
> and i was thinking of using the server to play with my friends, i think this isn't the right project! 😅

yea its meant for a "better offline experience" lol, you could consider using [gulag](https://github.com/osuAkatsuki/gulag) if you want to but I think its WAY more dev friendly then user friendly nowadays

**Comment by SrIzan10** [comment]
Well, thank you SO much! closing issue and not bothering you again...
