### ISSUE TITLE
configuration each opening

### ISSUE THREAD

**Issue by lokillo999** [coverosu/local-osu-server#9]
every time i start the server it sends me to the general configuration and that happens every time i open the main.py file
![image](https://user-images.githubusercontent.com/19214569/154835645-15f05436-1fd2-49f2-b79d-f9868eecdde9.png)

**Comment by coverosu** [comment]
Your version file might not be up to date, check if its at `'1.6.3'` in `version.py`

**Comment by lokillo999** [comment]
yep its V1.6.3
![image](https://user-images.githubusercontent.com/19214569/154837547-e221b396-e1b1-4142-bf3f-a5448524bad7.png)

**Comment by coverosu** [comment]
Try reinstalling the code? I can look into in the morning if it doesn't work otherwise!
